version: "3.8"

services:
  rabbitmq:
    image: rabbitmq:3.12-management
    ports:
      - "15672:15672"
      - "5672:5672"
    volumes:
      - rabbit_data:/var/lib/rabbitmq/mnesia
    env_file: ./.env
  zipkin:
    image: openzipkin/zipkin:3
    ports:
      - "9411:9411"

volumes:
  api_data: {}
  rabbit_data: {}